apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-observability
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.22.0
      helm:
        valueFiles:
          - $values/charts/prometheus/values.yaml
    - repoURL: https://github.com/devoriales/argocd-multiple-sources-tutorial
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
